build:
  maxIssues: 0 # Fail the build if any issues are found

config:
  validation: true
  warningsAsErrors: false


# Complexity

complexity:
  active: true

  CyclomaticComplexMethod:
    active: true
    threshold: 30

  LongMethod:
    active: true
    threshold: 60
    ignoreAnnotated:
      - 'Composable'

  LongParameterList:
    active: true
    functionThreshold: 8  # Composables often have many parameters
    constructorThreshold: 8
    ignoreAnnotated:
      - 'Composable'

  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInObjects: 15

  NestedBlockDepth:
    active: true
    threshold: 4

# Exceptions

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  RethrowCaughtException:
      active: false
  SwallowedException:
      active: false

# Naming

naming:
  active: true

  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'  # Allows Composable PascalCase names

  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'

  VariableNaming:
    active: true

# Style

style:
  active: true

  NewLineAtEndOfFile:
    active: false

  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true

  MaxLineLength:
    active: true
    maxLineLength: 140

  WildcardImport:
    active: true
    excludeImports:
      - 'androidx.compose.material3.*'
      - 'androidx.compose.ui.*'

  UnusedImports:
    active: true

  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'

  ReturnCount:
    active: true
    max: 4

# Potential Bugs

potential-bugs:
  active: true

  LateinitUsage:
    active: true

  UnsafeCallOnNullableType:
    active: true

# ─────────────────────────────────────────
# Coroutines
# ─────────────────────────────────────────
coroutines:
  active: true

  GlobalCoroutineUsage:
    active: true

  RedundantSuspendModifier:
    active: true

  SuspendFunWithFlowReturnType:
    active: true


# Empty blocks

empty-blocks:
  active: true

  EmptyCatchBlock:
    active: true

  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

# Performance

performance:
  active: true

  ArrayPrimitive:
    active: true

  ForEachOnRange:
    active: true
